language: python
sudo: false
python:
    - "3.4"
    - "3.5"
    - "3.6"
env:
    - IPYTHON_INSTALL='pip install ipython' MPL_INSTALL='pip install matplotlib'
matrix:
    include:
        - python: "2.6"
          env: >
            IPYTHON_INSTALL='pip install ipython==1.2.1'
            MPL_INSTALL='pip install matplotlib<2.0'
        - python: "2.7"
          env: >
            IPYTHON_INSTALL='pip install ipython>=5,<6'
            MPL_INSTALL='pip install matplotlib'
        - python: "3.3"
          env: >
            IPYTHON_INSTALL='pip install ipython'
            MPL_INSTALL='pip install matplotlib<2.0'
        - python: "pypy2.7-5.8.0"
          env: >
            IPYTHON_INSTALL='pip install ipython>=5,<6'
            MPL_INSTALL='echo "not installing matplotlib on pypy"'
        - python: "pypy3.5-5.8.0"
          env: >
            IPYTHON_INSTALL='pip install ipython'
            MPL_INSTALL='echo "not installing matplotlib on pypy"'
install:
    - pip install --upgrade pip
    - $IPYTHON_INSTALL
    - $MPL_INSTALL
    - pip install ipythonblocks
    - pip install .
    - pip install pytest-cov
    - pip install coveralls
script:
    - py.test --cov palettable --cov-report term-missing
after_success:
    - coveralls
